In [1]:
with open("data/text8", "r") as f:
    text = f.read()
print(len(text))

100000000


In [3]:
from src.utils import tokenize

In [4]:
tokenized_text = tokenize(text)

In [5]:
tokenized_text

['anarchism',
 'originated',
 'as',
 'a',
 'term',
 'of',
 'abuse',
 'first',
 'used',
 'against',
 'early',
 'working',
 'class',
 'radicals',
 'including',
 'the',
 'diggers',
 'of',
 'the',
 'english',
 'revolution',
 'and',
 'the',
 'sans',
 'culottes',
 'of',
 'the',
 'french',
 'revolution',
 'whilst',
 'the',
 'term',
 'is',
 'still',
 'used',
 'in',
 'a',
 'pejorative',
 'way',
 'to',
 'describe',
 'any',
 'act',
 'that',
 'used',
 'violent',
 'means',
 'to',
 'destroy',
 'the',
 'organization',
 'of',
 'society',
 'it',
 'has',
 'also',
 'been',
 'taken',
 'up',
 'as',
 'a',
 'positive',
 'label',
 'by',
 'self',
 'defined',
 'anarchists',
 'the',
 'word',
 'anarchism',
 'is',
 'derived',
 'from',
 'the',
 'greek',
 'without',
 'archons',
 'ruler',
 'chief',
 'king',
 'anarchism',
 'as',
 'a',
 'political',
 'philosophy',
 'is',
 'the',
 'belief',
 'that',
 'rulers',
 'are',
 'unnecessary',
 'and',
 'should',
 'be',
 'abolished',
 'although',
 'there',
 'are',
 'differing',
 '

In [6]:
from collections import Counter


In [10]:
word_counter = Counter()

In [14]:
word_counts  = Counter(tokenized_text)

In [20]:
dict(word_counts)

{'anarchism': 303,
 'originated': 572,
 'as': 131815,
 'a': 325873,
 'term': 7219,
 'of': 593677,
 'abuse': 563,
 'first': 28810,
 'used': 22737,
 'against': 8432,
 'early': 10172,
 'working': 2271,
 'class': 3412,
 'radicals': 116,
 'including': 9633,
 'the': 1061396,
 'diggers': 25,
 'english': 11868,
 'revolution': 2029,
 'and': 416629,
 'sans': 68,
 'culottes': 6,
 'french': 8736,
 'whilst': 481,
 'is': 183153,
 'still': 7378,
 'in': 372201,
 'pejorative': 114,
 'way': 6433,
 'to': 316376,
 'describe': 1352,
 'any': 11803,
 'act': 3502,
 'that': 109510,
 'violent': 653,
 'means': 4165,
 'destroy': 466,
 'organization': 2374,
 'society': 4067,
 'it': 73334,
 'has': 37866,
 'also': 44358,
 'been': 25383,
 'taken': 3043,
 'up': 12445,
 'positive': 1254,
 'label': 646,
 'by': 111831,
 'self': 2879,
 'defined': 2449,
 'anarchists': 203,
 'word': 5678,
 'derived': 1701,
 'from': 72871,
 'greek': 4577,
 'without': 5661,
 'archons': 10,
 'ruler': 617,
 'chief': 2130,
 'king': 7456,
 'polit

In [15]:
word_counts.keys()

dict_keys(['anarchism', 'originated', 'as', 'a', 'term', 'of', 'abuse', 'first', 'used', 'against', 'early', 'working', 'class', 'radicals', 'including', 'the', 'diggers', 'english', 'revolution', 'and', 'sans', 'culottes', 'french', 'whilst', 'is', 'still', 'in', 'pejorative', 'way', 'to', 'describe', 'any', 'act', 'that', 'violent', 'means', 'destroy', 'organization', 'society', 'it', 'has', 'also', 'been', 'taken', 'up', 'positive', 'label', 'by', 'self', 'defined', 'anarchists', 'word', 'derived', 'from', 'greek', 'without', 'archons', 'ruler', 'chief', 'king', 'political', 'philosophy', 'belief', 'rulers', 'are', 'unnecessary', 'should', 'be', 'abolished', 'although', 'there', 'differing', 'interpretations', 'what', 'this', 'refers', 'related', 'social', 'movements', 'advocate', 'elimination', 'authoritarian', 'institutions', 'particularly', 'state', 'anarchy', 'most', 'use', 'does', 'not', 'imply', 'chaos', 'nihilism', 'or', 'anomie', 'but', 'rather', 'harmonious', 'anti', 'place

In [18]:
word_counts.values()

dict_values([303, 572, 131815, 325873, 7219, 593677, 563, 28810, 22737, 8432, 10172, 2271, 3412, 116, 9633, 1061396, 25, 11868, 2029, 416629, 68, 6, 8736, 481, 183153, 7378, 372201, 114, 6433, 316376, 1352, 11803, 3502, 109510, 653, 4165, 466, 2374, 4067, 73334, 37866, 44358, 25383, 3043, 12445, 1254, 646, 111831, 2879, 2449, 203, 5678, 1701, 72871, 4577, 5661, 10, 617, 2130, 7456, 6970, 2758, 1572, 687, 76527, 146, 5113, 61281, 399, 9286, 22707, 231, 395, 8581, 58832, 1570, 3536, 4307, 1002, 331, 216, 185, 1021, 2882, 12904, 109, 25563, 14011, 5221, 44033, 257, 331, 42, 68945, 7, 35358, 4605, 28, 3103, 5345, 1483, 1139, 67, 4435, 2215, 8244, 3768, 272, 2231, 404, 1579, 381, 1165, 169, 12363, 1265, 895, 167, 28553, 2404, 399, 5684, 15861, 1870, 15574, 4727, 61925, 337, 3242, 9388, 781, 485, 4125, 95603, 999, 956, 160, 2241, 1041, 171, 31, 5160, 1066, 8700, 1726, 12623, 6184, 112807, 1003, 91250, 1153, 169, 1224, 88, 247, 395, 39, 745, 39086, 59, 197, 2018, 1492, 122, 716, 68, 7435, 281

In [19]:
sorted_vocab = sorted(word_counts.values(), reverse=True)
sorted_vocab

[1061396,
 593677,
 416629,
 411764,
 372201,
 325873,
 316376,
 264975,
 250430,
 192644,
 183153,
 131815,
 125285,
 118445,
 116710,
 115789,
 114775,
 112807,
 111831,
 109510,
 108182,
 102145,
 99683,
 95603,
 91250,
 76527,
 73334,
 72871,
 68945,
 62603,
 61925,
 61281,
 58832,
 54788,
 54576,
 53573,
 44358,
 44033,
 39712,
 39086,
 37866,
 35358,
 32433,
 31523,
 29567,
 28810,
 28553,
 28161,
 28100,
 26229,
 26223,
 25563,
 25519,
 25383,
 24413,
 24096,
 23997,
 23770,
 22737,
 22707,
 21125,
 20623,
 20484,
 20477,
 20412,
 19864,
 19463,
 19206,
 19115,
 18807,
 17949,
 17581,
 17516,
 17377,
 17236,
 16155,
 15861,
 15737,
 15574,
 15122,
 14935,
 14916,
 14696,
 14629,
 14578,
 14494,
 14437,
 14420,
 14151,
 14011,
 13380,
 13296,
 12987,
 12904,
 12722,
 12623,
 12560,
 12445,
 12363,
 12347,
 12275,
 11931,
 11868,
 11847,
 11803,
 11755,
 11753,
 11721,
 11701,
 11537,
 11536,
 11426,
 11399,
 11323,
 11285,
 10976,
 10971,
 10691,
 10629,
 10627,
 10572,
 10561,
 

In [1]:
import torch

In [17]:
input_words = torch.randint(0, 5, (10,)) .to(float)
input_words

tensor([1., 0., 1., 3., 4., 3., 4., 1., 1., 2.], dtype=torch.float64)

In [44]:
in_embed = torch.arange(1,26).view((5,5)).to(float)
in_embed

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.]], dtype=torch.float64)

In [45]:
norma = torch.norm(in_embed, dim=1, keepdim=True)
norma

tensor([[ 7.4162],
        [18.1659],
        [29.2404],
        [40.3733],
        [51.5267]], dtype=torch.float64)

In [51]:
norm_prod = norma @ norma.T
norm_prod

tensor([[  55.0000,  134.7219,  216.8525,  299.4161,  382.1322],
        [ 134.7219,  330.0000,  531.1779,  733.4167,  936.0288],
        [ 216.8525,  531.1779,  855.0000, 1180.5295, 1506.6602],
        [ 299.4161,  733.4167, 1180.5295, 1630.0000, 2080.3005],
        [ 382.1322,  936.0288, 1506.6602, 2080.3005, 2655.0000]],
       dtype=torch.float64)

In [53]:
in_embed/norm_prod

tensor([[0.0182, 0.0148, 0.0138, 0.0134, 0.0131],
        [0.0445, 0.0212, 0.0151, 0.0123, 0.0107],
        [0.0507, 0.0226, 0.0152, 0.0119, 0.0100],
        [0.0534, 0.0232, 0.0152, 0.0117, 0.0096],
        [0.0550, 0.0235, 0.0153, 0.0115, 0.0094]], dtype=torch.float64)

In [19]:
torch.multinomial(input_words, 3)

tensor([0, 5, 3])

In [29]:
new = torch.arange(1,19).view(2,3,3)
new

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [32]:
v = torch.ones(2,3)
v

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
new.transpose(0,1)

tensor([[[ 1,  2,  3],
         [10, 11, 12]],

        [[ 4,  5,  6],
         [13, 14, 15]],

        [[ 7,  8,  9],
         [16, 17, 18]]])

In [40]:
hola = new.transpose(0,1)*v
hola

tensor([[[ 1.,  2.,  3.],
         [10., 11., 12.]],

        [[ 4.,  5.,  6.],
         [13., 14., 15.]],

        [[ 7.,  8.,  9.],
         [16., 17., 18.]]])

In [42]:
torch.sum(hola, 0)

tensor([[12., 15., 18.],
        [39., 42., 45.]])

In [54]:
for i in range(4, 1, -1):
    print(i)

4
3
2
